const initialData = {
  Restaurants: [
    { data: 'Name', purpose: 'To identify and address customers, manage reservations, and personalize services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate booking confirmations, service updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, deposits, and refunds.' },
    { data: 'Order Details', purpose: 'To fulfill orders, manage delivery, and personalize services.' },
    { data: 'Dietary Preferences', purpose: 'To cater to specific dietary needs and preferences.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Vehicle Information (license plate, model)', purpose: 'To manage parking services and ensure vehicle security.' },
  ],
  Hotel: [
    { data: 'Name', purpose: 'To identify and address guests, manage reservations, and personalize services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate booking confirmations, service updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, deposits, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Address', purpose: 'To verify booking details, facilitate billing, and for marketing purposes.' },
    { data: 'Date of Birth', purpose: 'To ensure age-related compliance, personalize services, and for marketing purposes.' },
    { data: 'Booking History', purpose: 'To manage reservations, provide personalized services, and for market analysis.' },
    { data: 'Preferences and Special Requests', purpose: 'To enhance guest experience by catering to specific needs and preferences.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
    { data: 'Social Media Profiles', purpose: 'To interact with guests on social media platforms, for marketing and promotional activities.' },
    { data: 'Travel Companion Information', purpose: 'To manage group bookings and personalize services for all guests in the booking.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
    { data: 'Health Information (allergies, disabilities)', purpose: 'To ensure guest safety and provide appropriate accommodations and services.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance guest satisfaction.' },
    { data: 'Vehicle Information (license plate, model)', purpose: 'To manage parking services and ensure vehicle security.' },
  ],
  Hospitals_and_Healthcare: [
    { data: 'Name', purpose: 'To identify patients, manage appointments, and personalize care.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate appointment reminders, service updates, and health tips.' },
    { data: 'Health Information (medical history, conditions)', purpose: 'To provide appropriate medical care and for legal compliance.' },
    { data: 'Payment Information (insurance details, credit card)', purpose: 'To process payments, insurance claims, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Emergency Contact Information', purpose: 'To contact family or friends in case of emergency.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve healthcare services, address concerns, and enhance patient satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Educational_Institutions: [
    { data: 'Name', purpose: 'To identify and address students, manage enrollments, and personalize learning experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate enrollment confirmations, service updates, and academic progress.' },
    { data: 'Academic Records', purpose: 'To manage student progress, generate transcripts, and for accreditation purposes.' },
    { data: 'Payment Information (tuition details, credit card)', purpose: 'To process payments, scholarships, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Date of Birth', purpose: 'To ensure age-related compliance and for enrollment purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve educational services, address concerns, and enhance student satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Ecommerce: [
    { data: 'Name', purpose: 'To identify and address customers, manage orders, and personalize shopping experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate order confirmations, delivery updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, refunds, and manage fraud prevention.' },
    { data: 'Order Details', purpose: 'To fulfill orders, manage delivery, and personalize services.' },
    { data: 'Shipping Address', purpose: 'To deliver products and verify customer identity.' },
    { data: 'Browsing History', purpose: 'To personalize shopping experiences and for marketing purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
  ],
  Charity: [
    { data: 'Name', purpose: 'To identify and address donors, manage donations, and personalize communications.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate donation confirmations, service updates, and fundraising campaigns.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process donations, provide receipts, and manage refunds.' },
    { data: 'Donation History', purpose: 'To track donor contributions and provide personalized engagement.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance donor satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Social_Media: [
    { data: 'Name', purpose: 'To identify and address users, manage profiles, and personalize content.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate account notifications, service updates, and promotional offers.' },
    { data: 'Profile Information', purpose: 'To manage user profiles, personalize content, and for account verification.' },
    { data: 'Social Media Activity', purpose: 'To improve platform functionality, personalize content, and for analytical purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve platform functionality, ensure security, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance user satisfaction.' },
  ],
  Tech_Manufacturing: [
    { data: 'Name', purpose: 'To identify and address employees, manage HR records, and personalize employee experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
  Manufacturing: [
    { data: 'Name', purpose: 'To identify and address workers, manage payroll, and personalize HR services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
  Transportation_and_Warehousing: [
    { data: 'Name', purpose: 'To identify and address employees, manage payroll, and personalize HR services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
  Retail: [
    { data: 'Name', purpose: 'To identify customers and manage customer accounts.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate order confirmations, delivery updates, and promotional offers.' },
    { data: 'Address', purpose: 'To deliver products, send billing information, and facilitate returns.' },
    { data: 'Date of Birth', purpose: 'To verify identity, offer age-related discounts, and for marketing purposes.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, refunds, and manage billing.' },
    { data: 'Purchase History', purpose: 'To manage orders, provide personalized recommendations, and for market analysis.' },
    { data: 'Loyalty Program Information', purpose: 'To manage loyalty points, provide membership benefits, and send personalized offers.' },
    { data: 'Preferences and Interests', purpose: 'To personalize shopping experience and recommend products.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve products and services, address customer concerns, and enhance satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
    { data: 'Browsing History', purpose: 'To personalize website content, recommend products, and for market analysis.' },
    { data: 'Social Media Profiles', purpose: 'To interact with customers on social media platforms and for marketing and promotional activities.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective customer support and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To optimize delivery services, manage store locations, and enhance customer experience.' },
    { data: 'Wish Lists', purpose: 'To manage customer preferences and provide personalized recommendations.' },
    { data: 'Newsletter Subscription Details', purpose: 'To send newsletters, promotional offers, and updates about products and services.' },
    { data: 'Returns and Complaints Records', purpose: 'To manage returns, process refunds, and address customer complaints.' },
    { data: 'Health Information (allergies, dietary preferences)', purpose: 'To provide safe and appropriate product recommendations, especially for food and health products.' },
    { data: 'Employment Information (for store employees)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'Device Information (for app users)', purpose: 'To enhance app functionality, ensure security, and for user experience analysis.' },
  ],
  Construction: [
    { data: 'Name', purpose: 'To identify employees, clients, and subcontractors, and manage records.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with employees, clients, suppliers, and subcontractors about projects, updates, and other relevant information.' },
    { data: 'Address', purpose: 'To send invoices, project updates, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage employment records.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure security.' },
    { data: 'Employment Information (position, department, qualifications)', purpose: 'To manage HR functions, payroll, and employee benefits, and verify qualifications.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Social Security Number', purpose: 'To verify identity, process payroll, and comply with legal requirements.' },
    { data: 'Health and Safety Information', purpose: 'To ensure compliance with health and safety regulations and provide appropriate accommodations and support services.' },
    { data: 'Emergency Contact Information', purpose: 'To inform designated persons in case of emergencies.' },
    { data: 'Project History', purpose: 'To manage project records and ensure quality control.' },
    { data: 'Performance Records', purpose: 'To evaluate employee and subcontractor performance, manage promotions, and address disciplinary issues.' },
    { data: 'IP Address and Device Information', purpose: 'To improve IT infrastructure, ensure security, and for analytical purposes.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance client and employee satisfaction.' },
    { data: 'Supplier and Subcontractor Information', purpose: 'To manage relationships, orders, and payments with suppliers and subcontractors.' },
    { data: 'Customer Project History', purpose: 'To manage projects, provide customer support, and for market analysis.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To optimize logistics, manage site locations, and enhance project management.' },
    { data: 'Vehicle Information (license plate, model)', purpose: 'To manage company vehicle fleet and ensure security.' },
    { data: 'Training Records', purpose: 'To track employee training and ensure compliance with industry standards.' },
    { data: 'Insurance Information', purpose: 'To manage insurance claims and ensure compliance with legal and regulatory requirements.' },
    { data: 'Contract Details', purpose: 'To manage contracts with clients, suppliers, and subcontractors, and ensure legal compliance.' },
    { data: 'Equipment Usage Data', purpose: 'To manage and optimize the use of construction equipment.' },
  ],
  Insurance: [
    { data: 'Name', purpose: 'To identify policyholders and manage records.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with policyholders about policy updates, claims, and other relevant information.' },
    { data: 'Address', purpose: 'To send policy documents, billing information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, determine eligibility for coverage, and calculate premiums.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure security.' },
    { data: 'Social Security Number', purpose: 'To verify identity, process claims, and comply with legal requirements.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Employment Information (occupation, income)', purpose: 'To assess risk, determine eligibility for coverage, and calculate premiums.' },
    { data: 'Health Information (medical history, current conditions)', purpose: 'To underwrite health and life insurance policies, assess risk, and process claims.' },
    { data: 'Claims History', purpose: 'To evaluate and process insurance claims, detect fraud, and determine eligibility for coverage.' },
    { data: 'Policy Details', purpose: 'To manage and administer insurance policies.' },
    { data: 'Beneficiary Information', purpose: 'To manage policy benefits and process claims.' },
    { data: 'Vehicle Information (make, model, VIN)', purpose: 'To underwrite auto insurance policies, assess risk, and process claims.' },
    { data: 'Property Information (home details, value)', purpose: 'To underwrite property insurance policies, assess risk, and process claims.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve online services, ensure security, and for analytical purposes.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To assess risk, manage claims, and optimize service delivery.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers.' },
    { data: 'Family Information (dependents, marital status)', purpose: 'To determine eligibility for coverage, calculate premiums, and manage policy benefits.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage policyholder disputes.' },
    { data: 'Travel Information', purpose: 'To underwrite travel insurance policies, assess risk, and process claims.' },
    { data: 'Professional Licenses and Certifications', purpose: 'To verify qualifications for professional liability insurance.' },
    { data: 'Educational Background', purpose: 'To assess risk and determine eligibility for certain types of insurance coverage.' },
  ],
  Banks: [
    { data: 'Name', purpose: 'To identify account holders and manage records.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with customers about account updates, transactions, and other relevant information.' },
    { data: 'Address', purpose: 'To send statements, billing information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage accounts.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure security.' },
    { data: 'Aadhaar Number or Similar Identifier', purpose: 'To verify identity, process tax reporting, and comply with legal requirements.' },
    { data: 'Financial Information (bank details, account numbers, credit card details)', purpose: 'To manage accounts, process transactions, and handle financial operations.' },
    { data: 'Employment Information (occupation, income)', purpose: 'To assess creditworthiness, determine eligibility for loans, and comply with regulatory requirements.' },
    { data: 'Transaction History', purpose: 'To monitor account activity, detect fraud, and provide customer support.' },
    { data: 'Account Balances', purpose: 'To manage accounts, provide statements, and offer financial products.' },
    { data: 'Credit History', purpose: 'To assess creditworthiness and determine eligibility for loans and credit products.' },
    { data: 'Loan and Mortgage Details', purpose: 'To manage loan accounts, process applications, and comply with regulatory requirements.' },
    { data: 'Investment Information', purpose: 'To provide investment services, manage portfolios, and offer financial advice.' },
    { data: 'Beneficiary Information', purpose: 'To manage account benefits and process claims.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve online banking services, ensure security, and for analytical purposes.' },
    { data: 'Geolocation Data', purpose: 'To detect and prevent fraud, optimize service delivery, and enhance security.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers.' },
    { data: 'Tax Information', purpose: 'To comply with tax reporting requirements and manage account taxation.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage account holder disputes.' },
    { data: 'Family Information (dependents, marital status)', purpose: 'To determine eligibility for certain products and services, and manage account benefits.' },
    { data: 'Biometric Data (fingerprints, facial recognition)', purpose: 'To verify identity and enhance security for online and mobile banking.' },
    { data: 'Security Questions and Answers', purpose: 'To authenticate users and ensure account security.' },
    { data: 'Travel Information', purpose: 'To detect and prevent fraud, and ensure the security of account transactions.' },
  ],
  Digital_Lending_Platforms: [
    { data: 'Name', purpose: 'To identify borrowers and manage loan applications.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with borrowers about loan applications, updates, and other relevant information.' },
    { data: 'Address', purpose: 'To verify identity, assess eligibility, and manage loan disbursements and repayments.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and assess creditworthiness.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity, ensure security, and comply with regulatory requirements.' },
    { data: 'Social Security Number', purpose: 'To verify identity, process credit checks, and comply with legal requirements.' },
    { data: 'Financial Information (income, employment details)', purpose: 'To assess creditworthiness, determine loan eligibility, and calculate loan terms.' },
    { data: 'Bank Account Information', purpose: 'To facilitate loan disbursements and repayments.' },
    { data: 'Credit History', purpose: 'To assess creditworthiness and determine loan eligibility.' },
    { data: 'Employment Information (occupation, employer)', purpose: 'To verify income, assess stability, and determine loan eligibility.' },
    { data: 'Loan Details', purpose: 'To manage loan accounts, process applications, and handle loan servicing.' },
    { data: 'Transaction History', purpose: 'To monitor repayment activity and assess borrower behavior.' },
    { data: 'IP Address and Device Information', purpose: 'To prevent fraud, ensure security, and for analytical purposes.' },
    { data: 'Geolocation Data', purpose: 'To verify borrower location and prevent fraud.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Social Media Profiles', purpose: 'To assess creditworthiness and verify identity through alternative means.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance borrower satisfaction.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage borrower disputes.' },
    { data: 'Insurance Information', purpose: 'To offer optional insurance products and manage insurance claims.' },
    { data: 'Biometric Data (fingerprints, facial recognition)', purpose: 'To enhance security for online loan applications and account access.' },
    { data: 'Education Information', purpose: 'To assess borrower qualifications and potential earning capacity.' },
    { data: 'Family Information (dependents, marital status)', purpose: 'To assess financial stability and obligations.' },
    { data: 'Vehicle Information (if applicable)', purpose: 'To evaluate collateral for secured loans.' },
    { data: 'Tax Information', purpose: 'To assess income and verify financial information provided by the borrower.' },
  ],
  Agriculture: [
    { data: 'Name', purpose: 'To identify employees, customers, and business partners.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with employees, customers, and suppliers about orders, updates, and other relevant information.' },
    { data: 'Address', purpose: 'To send invoices, shipping information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage employee records.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure security.' },
    { data: 'Social Security Number', purpose: 'To verify identity, process payroll, and comply with legal requirements.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Employment Information (position, department)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'Health and Safety Information', purpose: 'To ensure compliance with health and safety regulations and provide appropriate accommodations and support services.' },
    { data: 'Emergency Contact Information', purpose: 'To inform designated persons in case of emergencies.' },
    { data: 'Farming Operation Details', purpose: 'To manage agricultural operations, track production, and optimize resources.' },
    { data: 'Crop and Livestock Records', purpose: 'To monitor crop growth, manage inventory, and assess yield.' },
    { data: 'Machinery and Equipment Information', purpose: 'To track usage, maintenance schedules, and ensure equipment availability.' },
    { data: 'IP Address and Device Information', purpose: 'To improve IT infrastructure, ensure security, and for analytical purposes.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Supplier Information', purpose: 'To manage relationships, orders, and payments with suppliers.' },
    { data: 'Customer Purchase History', purpose: 'To manage orders, provide customer support, and for market analysis.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To optimize logistics, manage site locations, and enhance resource allocation.' },
    { data: 'Inventory Data', purpose: 'To manage inventory levels, track stock, and optimize storage.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage business disputes.' },
    { data: 'Weather and Environmental Data', purpose: 'To monitor weather patterns, assess risks, and plan farming activities.' },
    { data: 'Educational Background', purpose: 'To assess employee qualifications and provide relevant training.' },
  ],
  Pharmaceutical: [
    { data: 'Name', purpose: 'To identify patients, healthcare providers, and employees.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with patients, healthcare providers, and employees about medications, appointments, and updates.' },
    { data: 'Address', purpose: 'To send prescriptions, medication information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage patient records.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure compliance with regulations.' },
    { data: 'Health Information (medical history, current conditions)', purpose: 'To assess patient health, determine treatment plans, and monitor medication effectiveness.' },
    { data: 'Insurance Information', purpose: 'To process insurance claims, verify coverage, and manage billing.' },
    { data: 'Financial Information (billing details)', purpose: 'To process payments, manage billing, and handle financial transactions related to medications and services.' },
    { data: 'Prescription Details', purpose: 'To prescribe medications, manage dosages, and track medication history.' },
    { data: 'Adverse Event Reports', purpose: 'To monitor medication safety, identify potential side effects, and comply with regulatory reporting requirements.' },
    { data: 'Clinical Trial Data', purpose: 'To conduct research, assess medication efficacy, and obtain regulatory approvals.' },
    { data: 'Employment Information (position, department)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'IP Address and Device Information', purpose: 'To improve IT infrastructure, ensure security, and for analytical purposes.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers related to medications and healthcare services.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve products and services, address concerns, and enhance patient and healthcare provider satisfaction.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage disputes related to medications and services.' },
    { data: 'Biometric Data (fingerprints, facial recognition)', purpose: 'To enhance security for accessing medications and medical records.' },
    { data: 'Genetic Information', purpose: 'To assess genetic predispositions, personalize treatment plans, and conduct research.' },
    { data: 'Educational Background', purpose: 'To assess healthcare provider qualifications, provide relevant training, and ensure compliance with regulations.' },
    { data: 'Family Medical History', purpose: 'To assess genetic predispositions and familial medical conditions that may impact treatment plans.' },
    { data: 'Supplier Information', purpose: 'To manage relationships with medication suppliers, track inventory, and ensure quality control.' },
    { data: 'Patient Support Program Participation', purpose: 'To enroll patients in support programs, provide assistance with medication costs, and monitor treatment adherence.' },
    { data: 'Research Participant Data', purpose: 'To collect data from research participants for clinical trials, observational studies, and other research initiatives.' },
  ],
  Car_Manufacturing: [
    { data: 'Name', purpose: 'To identify customers, employees, and business partners.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with customers, employees, and suppliers about orders, updates, and other relevant information.' },
    { data: 'Address', purpose: 'To send invoices, shipping information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage employee records.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure security.' },
    { data: 'Social Security Number', purpose: 'To verify identity, process payroll, and comply with legal requirements.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Employment Information (position, department)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'Vehicle Purchase Details', purpose: 'To process vehicle orders, manage deliveries, and provide customer support.' },
    { data: 'Vehicle Identification Number (VIN)', purpose: 'To identify specific vehicles and manage manufacturing and service records.' },
    { data: 'Vehicle Configuration Details', purpose: 'To customize vehicle features and options according to customer preferences.' },
    { data: 'Vehicle Usage Data', purpose: 'To monitor vehicle performance, conduct diagnostics, and provide maintenance recommendations.' },
    { data: 'Warranty Information', purpose: 'To manage warranty claims, provide service, and track vehicle maintenance history.' },
    { data: 'IP Address and Device Information', purpose: 'To improve vehicle technology, ensure security, and for analytical purposes.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve products and services, address concerns, and enhance customer satisfaction.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers related to vehicle purchases and services.' },
    { data: 'Geolocation Data', purpose: 'To optimize logistics, manage vehicle deliveries, and enhance service provision.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide customer support, and for compliance purposes.' },
    { data: 'Vehicle Service Records', purpose: 'To track maintenance history, schedule service appointments, and ensure vehicle safety.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage disputes related to vehicle sales and service.' },
    { data: 'Vehicle Telematics Data', purpose: 'To monitor vehicle usage, assess driving behavior, and offer value-added services such as navigation and roadside assistance.' },
  ],
  Gaming: [
    { data: 'Name', purpose: 'To identify players and personalize gaming experiences.' },
    { data: 'Contact Information (email, phone number)', purpose: 'To communicate with players regarding account management, updates, and promotional offers.' },
    { data: 'Username', purpose: 'To identify players within the gaming community and on gaming platforms.' },
    { data: 'Age/Birthdate', purpose: 'To comply with age restrictions for age-appropriate content and services.' },
    { data: 'Gender', purpose: 'To customize gaming experiences and analyze player demographics for marketing purposes.' },
    { data: 'Location Data (IP address, geolocation)', purpose: 'To provide region-specific content, localize services, and prevent fraud.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process in-game purchases, subscriptions, and microtransactions.' },
    { data: 'Gameplay Data (progress, achievements)', purpose: 'To track player progress, award achievements, and personalize gaming experiences.' },
    { data: 'Device Information (hardware, software)', purpose: 'To optimize game performance, provide technical support, and ensure compatibility.' },
    { data: 'Chat Logs', purpose: 'To facilitate communication between players and moderators, enforce community guidelines, and prevent harassment.' },
    { data: 'Social Media Integration', purpose: 'To enable social interactions within games, share achievements, and invite friends to play.' },
    { data: 'Player Support Interactions', purpose: 'To provide customer support, address technical issues, and resolve player inquiries.' },
    { data: 'Survey and Feedback Responses', purpose: 'To gather player feedback, improve game features, and enhance user satisfaction.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications, promotions, and announcements related to games and in-game content.' },
    { data: 'Biometric Data (if applicable)', purpose: 'To authenticate players for access to game content or features using biometric identification methods.' },
    { data: 'User-generated Content', purpose: 'To enable players to create and share custom content within games, such as mods, levels, or skins.' },
    { data: 'Cookies and Tracking Technologies', purpose: 'To personalize player experiences, analyze usage patterns, and improve game performance.' },
    { data: 'Advertising IDs', purpose: 'To track ad engagement, measure ad performance, and deliver targeted advertising within games.' },
    { data: 'Game Telemetry Data', purpose: 'To collect analytics on game usage, identify technical issues, and optimize game design and performance.' },
    { data: 'Voice Chat Recordings', purpose: 'To enable voice communication between players during multiplayer games.' },
    { data: 'User Profiles', purpose: 'To create and maintain player profiles, including avatars, stats, and preferences.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, respond to legal requests, and manage disputes.' },
  ],
  Food_and_Beverages: [
    { data: 'Name', purpose: 'To identify customers, employees, and business partners.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate with customers, employees, suppliers, and distributors about orders, updates, and other relevant information.' },
    { data: 'Address', purpose: 'To send invoices, shipping information, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify age for age-restricted products, loyalty programs, and promotions.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure legal compliance.' },
    { data: 'Social Security Number', purpose: 'For employment verification, tax purposes, and compliance with regulatory requirements.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Dietary Preferences', purpose: 'To offer personalized product recommendations, cater to specific dietary needs, and ensure compliance with dietary restrictions.' },
    { data: 'Purchase History', purpose: 'To analyze customer preferences, forecast demand, and offer targeted promotions.' },
    { data: 'Loyalty Program Information', purpose: 'To manage loyalty programs, track rewards, and provide personalized offers.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve products, gather customer insights, and enhance customer satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, track user behavior, and ensure security.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To provide customer support, address inquiries, and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To optimize delivery routes, target local promotions, and analyze market trends.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers.' },
    { data: 'Employment Information (position, department)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'Supplier Information', purpose: 'To manage relationships with suppliers, track orders, and ensure product quality.' },
    { data: 'Product Reviews', purpose: 'To gather customer feedback, improve products, and enhance brand reputation.' },
    { data: 'Allergies and Food Sensitivities', purpose: 'To ensure product safety, provide allergen information, and offer suitable alternatives.' },
    { data: 'Health Information (if relevant)', purpose: 'To comply with health regulations, provide nutritional information, and ensure product safety.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, process claims, and manage disputes.' },
  ],
  IT_Outsourcing: [
    { data: 'Name', purpose: 'To identify clients, employees, and business partners.' },
    { data: 'Contact Information (email, phone number)', purpose: 'To communicate with clients, employees, and stakeholders regarding services, updates, and support.' },
    { data: 'Address', purpose: 'To send invoices, deliver products, and correspondence.' },
    { data: 'Date of Birth', purpose: 'To verify identity, ensure age-related compliance, and manage employee records.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To verify identity and ensure legal compliance.' },
    { data: 'Social Security Number', purpose: 'For employment verification, tax purposes, and compliance with regulatory requirements.' },
    { data: 'Financial Information (bank details, credit card details)', purpose: 'To process payments, manage billing, and handle financial transactions.' },
    { data: 'Employment Information (position, department)', purpose: 'To manage HR functions, payroll, and employee benefits.' },
    { data: 'Technical Information (IP address, device ID)', purpose: 'To provide IT services, monitor network activity, and troubleshoot technical issues.' },
    { data: 'Usage Data (website interactions, software usage)', purpose: 'To improve service offerings, analyze usage patterns, and optimize user experience.' },
    { data: 'Communication Records (emails, calls)', purpose: 'To ensure effective communication, provide support, and for compliance purposes.' },
    { data: 'Geolocation Data', purpose: 'To optimize service delivery, provide location-based services, and analyze market trends.' },
    { data: 'Marketing Preferences', purpose: 'To send targeted marketing communications and promotional offers related to IT services.' },
    { data: 'Survey and Feedback Responses', purpose: 'To gather client feedback, improve services, and enhance customer satisfaction.' },
    { data: 'Device Information (hardware, software)', purpose: 'To ensure compatibility, provide technical support, and customize service delivery.' },
    { data: 'Biometric Data (if applicable)', purpose: 'To authenticate access to sensitive information or secure systems using biometric identification methods.' },
    { data: 'Legal Information (court orders, legal proceedings)', purpose: 'To comply with legal requirements, respond to legal requests, and manage disputes.' },
    { data: 'Software Licenses and Usage', purpose: 'To track software usage, manage licenses, and ensure compliance with licensing agreements.' },
    { data: 'Client Service Records', purpose: 'To track client interactions, manage service requests, and provide ongoing support.' },
    { data: 'Training Records', purpose: 'To track employee training and certifications, ensure compliance, and maintain professional standards.' },
    { data: 'Project Documentation', purpose: 'To manage project delivery, track progress, and document project requirements and outcomes.' },
    { data: 'Vendor and Partner Information', purpose: 'To manage relationships with vendors and partners, facilitate collaboration, and ensure service delivery.' },
    { data: 'Incident and Security Logs', purpose: 'To monitor system security, detect and respond to security incidents, and ensure data protection.' },
    { data: 'Cloud Service Data', purpose: 'To store, process, and manage client data securely in cloud environments.' },
    { data: 'User Credentials', purpose: 'To authenticate user access to IT systems and services, and ensure data security.' },
  ]
};

export { initialData };