const initialData = {
  Restaurants: [
    { data: 'Name', purpose: 'To identify and address customers, manage reservations, and personalize services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate booking confirmations, service updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, deposits, and refunds.' },
    { data: 'Order Details', purpose: 'To fulfill orders, manage delivery, and personalize services.' },
    { data: 'Dietary Preferences', purpose: 'To cater to specific dietary needs and preferences.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Vehicle Information (license plate, model)', purpose: 'To manage parking services and ensure vehicle security.' },
  ],
  Hotel: [
    { data: 'Name', purpose: 'To identify and address guests, manage reservations, and personalize services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate booking confirmations, service updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, deposits, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Address', purpose: 'To verify booking details, facilitate billing, and for marketing purposes.' },
    { data: 'Date of Birth', purpose: 'To ensure age-related compliance, personalize services, and for marketing purposes.' },
    { data: 'Booking History', purpose: 'To manage reservations, provide personalized services, and for market analysis.' },
    { data: 'Preferences and Special Requests', purpose: 'To enhance guest experience by catering to specific needs and preferences.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
    { data: 'Social Media Profiles', purpose: 'To interact with guests on social media platforms, for marketing and promotional activities.' },
    { data: 'Travel Companion Information', purpose: 'To manage group bookings and personalize services for all guests in the booking.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
    { data: 'Health Information (allergies, disabilities)', purpose: 'To ensure guest safety and provide appropriate accommodations and services.' },
    { data: 'Survey and Feedback Responses', purpose: 'To improve services, address concerns, and enhance guest satisfaction.' },
    { data: 'Vehicle Information (license plate, model)', purpose: 'To manage parking services and ensure vehicle security.' },
  ],
  Hospitals_and_Healthcare: [
    { data: 'Name', purpose: 'To identify patients, manage appointments, and personalize care.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate appointment reminders, service updates, and health tips.' },
    { data: 'Health Information (medical history, conditions)', purpose: 'To provide appropriate medical care and for legal compliance.' },
    { data: 'Payment Information (insurance details, credit card)', purpose: 'To process payments, insurance claims, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Emergency Contact Information', purpose: 'To contact family or friends in case of emergency.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve healthcare services, address concerns, and enhance patient satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Educational_Institutions: [
    { data: 'Name', purpose: 'To identify and address students, manage enrollments, and personalize learning experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate enrollment confirmations, service updates, and academic progress.' },
    { data: 'Academic Records', purpose: 'To manage student progress, generate transcripts, and for accreditation purposes.' },
    { data: 'Payment Information (tuition details, credit card)', purpose: 'To process payments, scholarships, and refunds.' },
    { data: 'Identification Documents (passport, ID)', purpose: 'To comply with legal and regulatory requirements, verify identity, and ensure security.' },
    { data: 'Date of Birth', purpose: 'To ensure age-related compliance and for enrollment purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve educational services, address concerns, and enhance student satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Ecommerce: [
    { data: 'Name', purpose: 'To identify and address customers, manage orders, and personalize shopping experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate order confirmations, delivery updates, and promotional offers.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process payments, refunds, and manage fraud prevention.' },
    { data: 'Order Details', purpose: 'To fulfill orders, manage delivery, and personalize services.' },
    { data: 'Shipping Address', purpose: 'To deliver products and verify customer identity.' },
    { data: 'Browsing History', purpose: 'To personalize shopping experiences and for marketing purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance customer satisfaction.' },
    { data: 'Loyalty Program Information', purpose: 'To manage membership benefits, track loyalty points, and provide personalized offers.' },
  ],
  Charity: [
    { data: 'Name', purpose: 'To identify and address donors, manage donations, and personalize communications.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate donation confirmations, service updates, and fundraising campaigns.' },
    { data: 'Payment Information (credit card details)', purpose: 'To process donations, provide receipts, and manage refunds.' },
    { data: 'Donation History', purpose: 'To track donor contributions and provide personalized engagement.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance donor satisfaction.' },
    { data: 'IP Address and Device Information', purpose: 'To improve website functionality, ensure security, and for analytical purposes.' },
  ],
  Social_Media: [
    { data: 'Name', purpose: 'To identify and address users, manage profiles, and personalize content.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate account notifications, service updates, and promotional offers.' },
    { data: 'Profile Information', purpose: 'To manage user profiles, personalize content, and for account verification.' },
    { data: 'Social Media Activity', purpose: 'To improve platform functionality, personalize content, and for analytical purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve platform functionality, ensure security, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve services, address concerns, and enhance user satisfaction.' },
  ],
  Tech_Manufacturing: [
    { data: 'Name', purpose: 'To identify and address employees, manage HR records, and personalize employee experiences.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
  Manufacturing: [
    { data: 'Name', purpose: 'To identify and address workers, manage payroll, and personalize HR services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
  Transportation_and_Warehousing: [
    { data: 'Name', purpose: 'To identify and address employees, manage payroll, and personalize HR services.' },
    { data: 'Contact Information (phone number, email)', purpose: 'To communicate work-related notifications, service updates, and employee benefits.' },
    { data: 'Employee ID', purpose: 'To verify identity and manage employment records.' },
    { data: 'Payment Information (bank details)', purpose: 'To process salaries, reimbursements, and manage tax compliance.' },
    { data: 'Work Performance Data', purpose: 'To manage appraisals, promotions, and for training purposes.' },
    { data: 'IP Address and Device Information', purpose: 'To improve network security, ensure data protection, and for analytical purposes.' },
    { data: 'Feedback and Survey Responses', purpose: 'To improve employee satisfaction, address concerns, and enhance workplace culture.' },
  ],
};


export { initialData };