import React from 'react';
import '../styles/DpdpFaqs.css';

const DpdpFaqs = () => {
  const faqs = [
    {
      question: "What is the DPDP Act of India?",
      answer: "The DPDP (Data Protection and Privacy) Act of India is a comprehensive legislation aimed at safeguarding the privacy and personal data of individuals. It outlines the responsibilities of organizations in handling personal data and the rights of individuals in relation to their data."
    },
    {
      question: "How does your service help in complying with the DPDP Act?",
      answer: "Our service provides an end-to-end solution for compliance with the DPDP Act. We generate a comprehensive privacy policy and a robust FAQ chatbot that ensures all required information is readily available to users, thereby reducing the compliance burden on your organization."
    },
    {
      question: "Is the privacy policy generated customizable?",
      answer: "Yes, the privacy policy generated by our service is fully customizable. You can tailor it to suit the specific needs of your organization while ensuring it remains compliant with the DPDP Act."
    },
    {
      question: "How frequently is the information updated?",
      answer: "We continuously monitor updates to the DPDP Act and other relevant regulations. Our service ensures that your privacy policy and chatbot are always up-to-date with the latest legal requirements."
    },
    {
      question: "What kind of support do you provide?",
      answer: "We offer comprehensive support to ensure you get the most out of our service. This includes setup assistance, customization help, and ongoing updates to keep your privacy policy and chatbot compliant with the latest regulations."
    }
  ];

  return (
    <div className="faq-container">
      <header className="faq-header">
        <h1>Frequently Asked Questions</h1>
      </header>
      <main className="faq-main">
        {faqs.map((faq, index) => (
          <div className="faq-item" key={index}>
            <h3>{faq.question}</h3>
            <p>{faq.answer}</p>
          </div>
        ))}
      </main>
      <footer className="faq-footer">
        <p>&copy; 2024 Our Company. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default DpdpFaqs;
